apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    app: todo
spec:
  selector:
    matchLabels:
      app: todo
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: todo
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: todo
          image: "selisebt/todo-docsify:bf2a7e5d6800ac2d471911e99023e0cde2512143"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 8080
              name: todo
