name: K8S Manifest Update
on:
  push:
    branches:
      - "main"
jobs:
  update:
    env:
      container_image_tag: ${{ vars.DOCKER_REPO }}:${{github.sha}}
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Build
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: '${{ vars.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_PASSWORD }}'

      - name: Build and push Docker image
        id: 'docker-build'
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.container_image_tag }}
          cache-from: type=registry,ref=${{ vars.DOCKER_REPO }}:buildcache
          cache-to: type=registry,ref=${{ vars.DOCKER_REPO }}:buildcache,mode=max

      - name: Update Kubernetes manifest
        if: steps.docker-build.outcome == 'success'
        id: manifest-update
        run: |
          yq eval '.spec.template.spec.containers[0].image = "${{ env.container_image_tag }}"' -i ./k8s/deployment.yaml

      - name: Commit and push changes
        if: steps.manifest-update.outcome == 'success'
        id: manifest-push
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add ./k8s/deployment.yaml
          git commit -m "Update Kubernetes manifest"
          git push origin main

      - name: Send message 
        if: ${{ steps.manifest-push.outcome == 'success' }}
        uses: teknatha136/actions-google-chat-text-message@main
        with:
          google-chat-webhook: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          text-message: 'K8S Manifest Updated for `${{ env.container_image_tag }}`'